// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

void ui_gameScreen_screen_init(void)
{
    ui_gameScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_gameScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_Background, &ui_img_background_png);
    lv_obj_set_width(ui_Background, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Background, LV_SIZE_CONTENT);    /// 240
    lv_obj_clear_flag(ui_Background, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_EmbeddedTea = lv_label_create(ui_gameScreen);
    lv_obj_set_width(ui_EmbeddedTea, 320);
    lv_obj_set_height(ui_EmbeddedTea, 12);
    lv_obj_set_x(ui_EmbeddedTea, 0);
    lv_obj_set_y(ui_EmbeddedTea, 230);
    lv_label_set_text(ui_EmbeddedTea, "Embedded Tea");
    lv_obj_clear_flag(ui_EmbeddedTea, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_EmbeddedTea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EmbeddedTea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EmbeddedTea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EmbeddedTea, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EmbeddedTea, lv_color_hex(0xB2832C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EmbeddedTea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EmbeddedTea, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EmbeddedTea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EmbeddedTea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PillarD0 = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_PillarD0, &ui_img_pillard0_png);
    lv_obj_set_width(ui_PillarD0, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_PillarD0, LV_SIZE_CONTENT);    /// 79
    lv_obj_set_x(ui_PillarD0, 30);
    lv_obj_set_y(ui_PillarD0, 161);
    lv_obj_add_flag(ui_PillarD0, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PillarD0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_PillarU0 = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_PillarU0, &ui_img_pillaru0_png);
    lv_obj_set_width(ui_PillarU0, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_PillarU0, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_PillarU0, 30);
    lv_obj_set_y(ui_PillarU0, 0);
    lv_obj_add_flag(ui_PillarU0, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PillarU0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_PillarD1 = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_PillarD1, &ui_img_pillard1_png);
    lv_obj_set_width(ui_PillarD1, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_PillarD1, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_PillarD1, 150);
    lv_obj_set_y(ui_PillarD1, 214);
    lv_obj_add_flag(ui_PillarD1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PillarD1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_PillarU1 = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_PillarU1, &ui_img_pillaru1_png);
    lv_obj_set_width(ui_PillarU1, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_PillarU1, LV_SIZE_CONTENT);    /// 148
    lv_obj_set_x(ui_PillarU1, 150);
    lv_obj_set_y(ui_PillarU1, -2);
    lv_obj_add_flag(ui_PillarU1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PillarU1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_PillarD2 = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_PillarD2, &ui_img_pillard2_png);
    lv_obj_set_width(ui_PillarD2, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_PillarD2, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_PillarD2, 270);
    lv_obj_set_y(ui_PillarD2, 191);
    lv_obj_add_flag(ui_PillarD2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PillarD2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_PillarU2 = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_PillarU2, &ui_img_pillaru2_png);
    lv_obj_set_width(ui_PillarU2, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_PillarU2, LV_SIZE_CONTENT);    /// 91
    lv_obj_set_x(ui_PillarU2, 270);
    lv_obj_set_y(ui_PillarU2, 0);
    lv_obj_add_flag(ui_PillarU2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PillarU2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_FlappyWingUp = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_FlappyWingUp, &ui_img_flappyup_png);
    lv_obj_set_width(ui_FlappyWingUp, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_FlappyWingUp, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_FlappyWingUp, 3);
    lv_obj_set_y(ui_FlappyWingUp, 96);
    lv_obj_add_flag(ui_FlappyWingUp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_FlappyWingUp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Flappy = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_Flappy, &ui_img_flappy_png);
    lv_obj_set_width(ui_Flappy, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Flappy, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_Flappy, 3);
    lv_obj_set_y(ui_Flappy, 96);
    lv_obj_clear_flag(ui_Flappy, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_GameScore = lv_label_create(ui_gameScreen);
    lv_obj_set_width(ui_GameScore, 29);
    lv_obj_set_height(ui_GameScore, 18);
    lv_obj_set_x(ui_GameScore, 3);
    lv_obj_set_y(ui_GameScore, -73);
    lv_obj_set_align(ui_GameScore, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GameScore, "0");
    lv_obj_add_flag(ui_GameScore, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_GameScore, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_GameScore, lv_color_hex(0x1D1D1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GameScore, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_GameScore, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GameScore, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameOver = lv_label_create(ui_gameScreen);
    lv_obj_set_width(ui_GameOver, 92);
    lv_obj_set_height(ui_GameOver, 21);
    lv_obj_set_x(ui_GameOver, 6);
    lv_obj_set_y(ui_GameOver, -2);
    lv_obj_set_align(ui_GameOver, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GameOver, "Game Over");
    lv_obj_clear_flag(ui_GameOver, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_GameOver, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GameOver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GameOver, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlappyGameTitle = lv_img_create(ui_gameScreen);
    lv_img_set_src(ui_FlappyGameTitle, &ui_img_flappygametext_png);
    lv_obj_set_width(ui_FlappyGameTitle, LV_SIZE_CONTENT);   /// 436
    lv_obj_set_height(ui_FlappyGameTitle, LV_SIZE_CONTENT);    /// 115
    lv_obj_set_x(ui_FlappyGameTitle, 82);
    lv_obj_set_y(ui_FlappyGameTitle, 92);
    lv_obj_clear_flag(ui_FlappyGameTitle,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Brightness = lv_obj_create(ui_gameScreen);
    lv_obj_remove_style_all(ui_Brightness);
    lv_obj_set_width(ui_Brightness, 320);
    lv_obj_set_height(ui_Brightness, 240);
    lv_obj_set_align(ui_Brightness, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Brightness, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Brightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Brightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}
