// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_gameScreen
void ui_gameScreen_screen_init(void);
lv_obj_t * ui_gameScreen;
lv_obj_t * ui_Background;
lv_obj_t * ui_EmbeddedTea;
lv_obj_t * ui_PillarD0;
lv_obj_t * ui_PillarU0;
lv_obj_t * ui_PillarD1;
lv_obj_t * ui_PillarU1;
lv_obj_t * ui_PillarD2;
lv_obj_t * ui_PillarU2;
lv_obj_t * ui_FlappyWingUp;
lv_obj_t * ui_Flappy;
lv_obj_t * ui_GameScore;
lv_obj_t * ui_GameOver;
lv_obj_t * ui_FlappyGameTitle;
lv_obj_t * ui_Brightness;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_gameScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_gameScreen);
}
