// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_gameScreen
void ui_gameScreen_screen_init(void);
extern lv_obj_t * ui_gameScreen;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_EmbeddedTea;
extern lv_obj_t * ui_PillarD0;
extern lv_obj_t * ui_PillarU0;
extern lv_obj_t * ui_PillarD1;
extern lv_obj_t * ui_PillarU1;
extern lv_obj_t * ui_PillarD2;
extern lv_obj_t * ui_PillarU2;
extern lv_obj_t * ui_FlappyWingUp;
extern lv_obj_t * ui_Flappy;
extern lv_obj_t * ui_GameScore;
extern lv_obj_t * ui_GameOver;
extern lv_obj_t * ui_FlappyGameTitle;
extern lv_obj_t * ui_Brightness;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/Background.png
LV_IMG_DECLARE(ui_img_pillard0_png);    // assets/PillarD0.png
LV_IMG_DECLARE(ui_img_pillaru0_png);    // assets/PillarU0.png
LV_IMG_DECLARE(ui_img_pillard1_png);    // assets/PillarD1.png
LV_IMG_DECLARE(ui_img_pillaru1_png);    // assets/PillarU1.png
LV_IMG_DECLARE(ui_img_pillard2_png);    // assets/PillarD2.png
LV_IMG_DECLARE(ui_img_pillaru2_png);    // assets/PillarU2.png
LV_IMG_DECLARE(ui_img_flappyup_png);    // assets/FlappyUp.png
LV_IMG_DECLARE(ui_img_flappy_png);    // assets/Flappy.png
LV_IMG_DECLARE(ui_img_flappygametext_png);    // assets/FlappyGameText.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
